#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'ark'
cookbook 'build-essential'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'openssl'
cookbook 'php'
cookbook 'php-fpm'
cookbook 'roundcube'
